"""Seed item bank for the MVP."""

from __future__ import annotations

from app.domain.models import ItemTemplate, QuestionOption


LIKERT_OPTIONS = [
    QuestionOption(key="strongly_disagree", text="非常不同意", score=-1.0),
    QuestionOption(key="disagree", text="不同意", score=-0.5),
    QuestionOption(key="neutral", text="不确定 / 看情况", score=0.0),
    QuestionOption(key="agree", text="同意", score=0.5),
    QuestionOption(key="strongly_agree", text="非常同意", score=1.0),
]


def make_item(
    item_id: str,
    prompt: str,
    dimension_weights: dict[str, float],
    scenario_tags: list[str],
    *,
    layer: str = "core",
    subdimension_weights: dict[str, float] | None = None,
    module_affinities: dict[str, float] | None = None,
    is_anchor: bool = False,
    allow_rewrite: bool = False,
) -> ItemTemplate:
    return ItemTemplate(
        id=item_id,
        prompt=prompt,
        question_type="likert_5",
        layer=layer,
        dimension_weights=dimension_weights,
        subdimension_weights=subdimension_weights or {},
        module_affinities=module_affinities or {},
        scenario_tags=scenario_tags,
        is_anchor=is_anchor,
        allow_rewrite=allow_rewrite,
        options=LIKERT_OPTIONS,
    )


def build_seed_item_bank() -> list[ItemTemplate]:
    return [
        make_item("core-social-1", "第一次进一个新组，桌上已经安静了半分钟，我多半会先开口把场子启动起来。", {"social_initiative": 1.0}, ["study", "unknown_group"]),
        make_item("core-social-2", "群聊一旦同时冒出几条线，我通常还能跟得上，不会很快被噪声耗空。", {"social_stimulation_tolerance": 1.0}, ["public", "high_stakes"]),
        make_item("core-social-3", "线上讨论刚有苗头但还没人定主线时，我常会先丢一个方向让大家接。", {"social_initiative": 0.8, "social_stimulation_tolerance": 0.2}, ["online", "work"]),
        make_item("core-social-4", "朋友刚聚齐、节目还没着落时，我往往会先提一个可执行的玩法。", {"social_initiative": 0.8, "novelty_seeking": 0.2}, ["leisure", "unknown_group"]),
        make_item("core-decision-1", "周围人的意见已经很整齐时，我还是会先把自己的判断做出来，再决定跟不跟。", {"autonomous_judgment": 1.0}, ["work", "study"]),
        make_item("core-decision-2", "信息没齐但窗口已经在关时，我通常能先定一个临时判断往前走。", {"autonomous_judgment": 0.75, "risk_tolerance": 0.25}, ["high_stakes", "project"]),
        make_item("core-decision-3", "大家都想等更稳的说法时，我往往愿意先给出一个能落地的版本。", {"autonomous_judgment": 0.7, "execution_drive": 0.3}, ["project", "team_mode"]),
        make_item("core-plan-1", "事情一开动之前，我会先想把步骤、顺序和节奏理顺。", {"planning_preference": 1.0}, ["work", "project"]),
        make_item("core-plan-2", "局面一直在变时，我也会尽量守住一条清楚的推进主线。", {"planning_preference": 0.8, "execution_drive": 0.2}, ["project", "high_stakes"]),
        make_item("core-plan-3", "无论是出门、协作还是临时做事，我常会顺手把顺序和优先级排出来。", {"planning_preference": 0.8, "social_initiative": 0.2}, ["leisure", "project"]),
        make_item("core-risk-1", "只要回报确实值得，我能接受方案里留下不小的未知数。", {"risk_tolerance": 1.0}, ["work", "high_stakes"]),
        make_item("core-risk-2", "一个新点子只要方向对，我愿意让它先跑一段，而不是等外界验证完再说。", {"risk_tolerance": 0.55, "novelty_seeking": 0.45}, ["creative_mode", "work"]),
        make_item("core-risk-3", "有些事正因为结果没人说得准，反而更容易让我想下场试试。", {"risk_tolerance": 0.55, "novelty_seeking": 0.45}, ["leisure", "creative_mode"]),
        make_item("core-abstract-1", "碰到新领域时，我第一反应通常是先摸清它背后的结构，而不是先背操作。", {"abstraction_tendency": 1.0}, ["study"]),
        make_item("core-abstract-2", "别人还在讲现象时，我常会顺手把问题往更一般的结构上提。", {"abstraction_tendency": 0.8, "autonomous_judgment": 0.2}, ["chat_mode", "study"]),
        make_item("core-abstract-3", "哪怕只是聊生活琐事，我也容易去想这背后有没有更普遍的模式。", {"abstraction_tendency": 0.9, "novelty_seeking": 0.1}, ["chat_mode", "leisure"]),
        make_item("core-novelty-1", "旧办法明明还能用，新工具或新路径出来时，我还是会被吸过去看看。", {"novelty_seeking": 1.0}, ["leisure", "work"]),
        make_item("core-competition-1", "团队做事时，比起“顺利做完”，我更容易被“能不能做得更强”拉起状态。", {"competition_cooperation": 1.0}, ["team_mode", "project"]),
        make_item("core-competition-2", "合作里只要带一点较劲意味，我的投入度通常会明显上来。", {"competition_cooperation": 0.85, "execution_drive": 0.15}, ["team_mode", "game"]),
        make_item("core-emotion-1", "被人打断、否掉或者当场质疑后，我一般能比较快把状态拉回来。", {"emotional_stability": 1.0}, ["conflict", "public"]),
        make_item("core-emotion-2", "起冲突时，我大体还能把自己的情绪和要处理的事分开。", {"emotional_stability": 0.8, "autonomous_judgment": 0.2}, ["conflict", "work"]),
        make_item("core-execution-1", "一旦决定要做，我通常会很快把它推成一个看得见的动作。", {"execution_drive": 1.0}, ["project", "work"]),
        make_item("core-execution-2", "事情往前推时就算遇到阻力，我也不会轻易松掉关键步骤。", {"execution_drive": 0.8, "emotional_stability": 0.2}, ["project", "high_stakes"]),
        make_item("core-social-5", "第一次进开源项目讨论区、大家还在互相试探时，我常会先抛个具体问题或 patch 思路。", {"social_initiative": 0.8, "autonomous_judgment": 0.2}, ["open_source", "online"], allow_rewrite=True),
        make_item("core-social-6", "在读书会、工作坊这类半熟半陌生的场子里，我一般不会一直只当背景板。", {"social_initiative": 0.8, "social_stimulation_tolerance": 0.2}, ["reading_group", "event"], allow_rewrite=True),
        make_item("core-social-7", "一个小圈子聊得很热却迟迟不落下一步时，我常会把话题往可执行的地方拽。", {"social_initiative": 0.7, "execution_drive": 0.3}, ["small_circle", "meeting"]),
        make_item("core-decision-4", "面对一群更资深、也更懂行的人时，我也不会轻易把自己的判断交出去。", {"autonomous_judgment": 0.85, "social_stimulation_tolerance": 0.15}, ["small_circle", "research"]),
        make_item("core-decision-5", "某个方案在圈内很流行，但要是我觉得它不适合眼前问题，我通常不会硬跟。", {"autonomous_judgment": 0.8, "risk_tolerance": 0.2}, ["maker", "project"], allow_rewrite=True),
        make_item("core-plan-4", "做播客、视频、长帖或专题时，我往往会先在脑里把结构分好层，再开始铺内容。", {"planning_preference": 0.85, "abstraction_tendency": 0.15}, ["creator", "writing"]),
        make_item("core-plan-5", "哪怕只是约朋友看展、跑活动或玩桌游，我也会自然开始排顺序和时间窗。", {"planning_preference": 0.75, "social_initiative": 0.25}, ["boardgame", "event"]),
        make_item("core-risk-4", "一个方向只要足够新鲜，哪怕教程很少，我也愿意边试边把坑补出来。", {"risk_tolerance": 0.65, "novelty_seeking": 0.35}, ["maker", "hackathon"], allow_rewrite=True),
        make_item("core-risk-5", "比起照着现成套路稳稳完成，我更容易被那种可能翻车、但成了会很新的路子吸引。", {"risk_tolerance": 0.55, "novelty_seeking": 0.45}, ["indie_game", "creative_mode"]),
        make_item("core-abstract-4", "看别人争论时，我常先注意到：他们可能根本不是在同一套框架里说话。", {"abstraction_tendency": 0.85, "autonomous_judgment": 0.15}, ["forum", "critical_thinking"]),
        make_item("core-abstract-5", "哪怕是在聊器材、工具或玩法，我也很容易继续追问背后的方法论是什么。", {"abstraction_tendency": 0.8, "novelty_seeking": 0.2}, ["maker", "gear"]),
        make_item("core-novelty-2", "新平台、新工作流或新圈子的最初混乱，通常不足以立刻把我劝退。", {"novelty_seeking": 0.8, "social_stimulation_tolerance": 0.2}, ["startup", "online"]),
        make_item("core-novelty-3", "一个小众领域只要有自己的黑话、规矩和内部趣味，我常会被那种内部世界感吸进去。", {"novelty_seeking": 0.85, "abstraction_tendency": 0.15}, ["fandom", "small_circle"], allow_rewrite=True),
        make_item("core-competition-3", "game jam、黑客松或小型竞赛里，只要出现“谁能做出更有意思的版本”，我的状态通常会被点亮。", {"competition_cooperation": 0.75, "execution_drive": 0.25}, ["hackathon", "game"]),
        make_item("core-emotion-3", "作品、观点或 patch 被当面挑毛病时，我通常还能比较快把注意力拉回问题本身。", {"emotional_stability": 0.8, "autonomous_judgment": 0.2}, ["open_source", "critique"]),
        make_item("core-emotion-4", "在高手很多的小圈子里发言，就算会被懂的人盯着看，我也不太会立刻缩回去。", {"emotional_stability": 0.7, "social_initiative": 0.3}, ["small_circle", "public"]),
        make_item("core-execution-3", "一个点子只要已经清楚到能试跑，我通常更想先搭个 rough 版本，而不是继续空谈。", {"execution_drive": 0.85, "risk_tolerance": 0.15}, ["maker", "prototype"]),
        make_item("core-execution-4", "维护知识库、整理资料或搭系统时，我不喜欢只把东西开个头就扔在那里。", {"execution_drive": 0.75, "planning_preference": 0.25}, ["notion", "knowledge_base"]),
        make_item("cross-social-plan-1", "接手陌生团队任务时，我常会一边招呼大家动起来，一边把流程先搭个骨架。", {"social_initiative": 0.65, "planning_preference": 0.35}, ["study", "unknown_group", "project"], module_affinities={"project_role": 0.7, "team_mode": 0.5}),
        make_item("cross-risk-exec-1", "一个高风险方案只要值得试，我多半会尽快把它推到试跑，而不只停在讨论。", {"risk_tolerance": 0.45, "execution_drive": 0.55}, ["work", "high_stakes"], module_affinities={"project_role": 0.6}),
        make_item("sub-social-entry-1", "进到陌生场合后，我一般不会在边上观望太久才加入谈话。", {"social_initiative": 0.7, "social_stimulation_tolerance": 0.3}, ["unknown_group", "public"], layer="sub", subdimension_weights={"entry_speed": 1.0}, module_affinities={"chat_mode": 0.5}),
        make_item("sub-social-entry-2", "刚进一个新群时，如果气氛不算冷，我通常会很快发第一条像样的话。", {"social_initiative": 0.75, "social_stimulation_tolerance": 0.25}, ["online", "unknown_group"], layer="sub", subdimension_weights={"entry_speed": 1.0}),
        make_item("sub-social-entry-3", "参加半熟不熟的聚会时，我不太会一直卡在“先看别人怎么聊”的状态。", {"social_initiative": 0.8, "social_stimulation_tolerance": 0.2}, ["leisure", "unknown_group"], layer="sub", subdimension_weights={"entry_speed": 1.0}),
        make_item("sub-social-entry-4", "线下活动被分到陌生小队时，我通常不会一直等别人先把气氛带起来。", {"social_initiative": 0.8, "planning_preference": 0.2}, ["event", "unknown_group"], layer="sub", subdimension_weights={"entry_speed": 1.0}, module_affinities={"team_mode": 0.4}),
        make_item("sub-social-familiar-1", "跟熟人在一起时，我说话的量和力度往往会明显往上走。", {"social_stimulation_tolerance": 0.7, "social_initiative": 0.3}, ["friends", "leisure"], layer="sub", subdimension_weights={"familiar_expression_intensity": 1.0}, module_affinities={"chat_mode": 0.7}),
        make_item("sub-social-familiar-2", "同一件事，在熟人面前我通常会讲得更放开、更有表情。", {"social_stimulation_tolerance": 0.75, "social_initiative": 0.25}, ["friends", "chat_mode"], layer="sub", subdimension_weights={"familiar_expression_intensity": 1.0}),
        make_item("sub-social-familiar-3", "跟很熟的人聊天时，我的精力通常不是被消耗，而是被带起来。", {"social_stimulation_tolerance": 0.8, "social_initiative": 0.2}, ["friends", "home"], layer="sub", subdimension_weights={"familiar_expression_intensity": 1.0}),
        make_item("sub-social-familiar-4", "一桌子几乎都是自己人时，我常会比平时更敢把气氛往上托。", {"social_stimulation_tolerance": 0.8, "novelty_seeking": 0.2}, ["friends", "dinner"], layer="sub", subdimension_weights={"familiar_expression_intensity": 1.0}),
        make_item("sub-social-conflict-1", "当群体里出现明显分歧时，只要我有看法，通常不会拖太久才表达。", {"social_initiative": 0.7, "emotional_stability": 0.3}, ["conflict", "team_mode"], layer="sub", subdimension_weights={"conflict_speaking_threshold": 1.0}, module_affinities={"conflict_mode": 0.8}),
        make_item("sub-social-conflict-2", "场面已经拧住而我又看得出症结时，我一般不会一直把话憋着。", {"social_initiative": 0.7, "emotional_stability": 0.3}, ["conflict", "work"], layer="sub", subdimension_weights={"conflict_speaking_threshold": 1.0}),
        make_item("sub-social-conflict-3", "那种大家都知道有问题却没人点破的局面，我通常很难装作没看见。", {"social_initiative": 0.75, "emotional_stability": 0.25}, ["study", "team_mode"], layer="sub", subdimension_weights={"conflict_speaking_threshold": 1.0}),
        make_item("sub-social-conflict-4", "评审会如果明显跑偏了，我倾向当场提醒，而不是拖到会后补一句。", {"social_initiative": 0.7, "execution_drive": 0.3}, ["work", "meeting"], layer="sub", subdimension_weights={"conflict_speaking_threshold": 1.0}, module_affinities={"conflict_mode": 0.7}),
        make_item("sub-decision-speed-1", "如果信息只够七成，但已经必须往前走，我通常不会一直卡在最后那三成。", {"autonomous_judgment": 0.75, "risk_tolerance": 0.25}, ["high_stakes", "work"], layer="sub", subdimension_weights={"low_info_decision_speed": 1.0}),
        make_item("sub-decision-speed-2", "一个决定继续拖下去已经开始变贵时，我一般不会无限追加信息再动。", {"autonomous_judgment": 0.75, "risk_tolerance": 0.25}, ["project", "high_stakes"], layer="sub", subdimension_weights={"low_info_decision_speed": 1.0}),
        make_item("sub-decision-speed-3", "如果局面要求先定一个版本再迭代，我通常能把那个版本先拍下来。", {"autonomous_judgment": 0.8, "execution_drive": 0.2}, ["work", "project"], layer="sub", subdimension_weights={"low_info_decision_speed": 1.0}),
        make_item("sub-decision-speed-4", "限时任务里只要再犹豫就会错过窗口，我往往能先做出一个能跑的决定。", {"autonomous_judgment": 0.7, "risk_tolerance": 0.3}, ["game", "high_stakes"], layer="sub", subdimension_weights={"low_info_decision_speed": 1.0}),
        make_item("sub-decision-authority-1", "就算已经有权威结论摆在那儿，我也更愿意把它当参考，而不是直接当答案。", {"autonomous_judgment": 0.8, "risk_tolerance": 0.2}, ["work", "study"], layer="sub", subdimension_weights={"authority_dependence": -1.0}),
        make_item("sub-decision-authority-2", "就算一个结论出自公认靠谱的人，我也还是会想先在脑内过一遍。", {"autonomous_judgment": 0.8, "abstraction_tendency": 0.2}, ["study", "chat_mode"], layer="sub", subdimension_weights={"authority_dependence": -1.0}),
        make_item("sub-decision-authority-3", "流程和经验打架时，我未必会本能地站到流程那一边。", {"autonomous_judgment": 0.7, "risk_tolerance": 0.3}, ["work", "project"], layer="sub", subdimension_weights={"authority_dependence": -1.0}),
        make_item("sub-decision-authority-4", "经典书单再有名，我也会先判断它到底适不适合眼下的问题。", {"autonomous_judgment": 0.75, "abstraction_tendency": 0.25}, ["study", "reading"], layer="sub", subdimension_weights={"authority_dependence": -1.0}),
        make_item("sub-decision-ambiguity-1", "方案还没长全时，我也能接受先走一步、边走边修。", {"risk_tolerance": 0.6, "autonomous_judgment": 0.4}, ["project", "high_stakes"], layer="sub", subdimension_weights={"ambiguity_tolerance": 1.0}),
        make_item("sub-decision-ambiguity-2", "只要大方向没坏，我通常可以接受事情在不够清楚的状态下先推进。", {"risk_tolerance": 0.65, "autonomous_judgment": 0.35}, ["project", "work"], layer="sub", subdimension_weights={"ambiguity_tolerance": 1.0}),
        make_item("sub-decision-ambiguity-3", "如果每一步都非得看得特别清楚才肯动，我反而会觉得整件事失去速度。", {"risk_tolerance": 0.7, "execution_drive": 0.3}, ["high_stakes", "creative_mode"], layer="sub", subdimension_weights={"ambiguity_tolerance": 1.0}),
        make_item("sub-decision-ambiguity-4", "做新东西时，要是非得先把所有未知都压平，我会觉得最好的时机已经过去了。", {"risk_tolerance": 0.7, "novelty_seeking": 0.3}, ["creative_mode", "startup"], layer="sub", subdimension_weights={"ambiguity_tolerance": 1.0}),
        make_item("sub-exec-start-1", "一个想法一旦成形，我往往不需要蓄很久就能把第一步做出来。", {"execution_drive": 0.7, "planning_preference": 0.3}, ["project", "creative_mode"], layer="sub", subdimension_weights={"start_speed": 1.0}, module_affinities={"creative_mode": 0.7}),
        make_item("sub-exec-start-2", "很多人还停在“想想看”的时候，我往往已经把第一步动起来了。", {"execution_drive": 0.8, "social_initiative": 0.2}, ["project", "team_mode"], layer="sub", subdimension_weights={"start_speed": 1.0}),
        make_item("sub-exec-start-3", "方案哪怕还不完美，只要方向八九不离十，我就能先把起点搭起来。", {"execution_drive": 0.75, "risk_tolerance": 0.25}, ["creative_mode", "work"], layer="sub", subdimension_weights={"start_speed": 1.0}),
        make_item("sub-exec-start-4", "临时起意的旅行、活动或合作，我通常也能很快把第一个动作敲定。", {"execution_drive": 0.75, "social_initiative": 0.25}, ["leisure", "project"], layer="sub", subdimension_weights={"start_speed": 1.0}),
        make_item("sub-plan-switch-1", "一个计划刚跑出手感时，我一般不会因为新点子冒出来就立刻换轨。", {"planning_preference": 0.8, "novelty_seeking": -0.2}, ["project", "creative_mode"], layer="sub", subdimension_weights={"switching_tendency": -1.0}),
        make_item("sub-plan-switch-2", "就算中途冒出一个看起来更酷的新方案，我通常也会先判断值不值得真的换轨。", {"planning_preference": 0.8, "novelty_seeking": -0.2}, ["creative_mode", "project"], layer="sub", subdimension_weights={"switching_tendency": -1.0}),
        make_item("sub-plan-switch-3", "事情已经做到半截时，我不太会因为一时兴起就整盘重来。", {"planning_preference": 0.85, "execution_drive": 0.15}, ["work", "project"], layer="sub", subdimension_weights={"switching_tendency": -1.0}),
        make_item("sub-plan-switch-4", "写到中段突然很想推翻重写时，我会先分辨那是洞见，还是单纯手痒。", {"planning_preference": 0.75, "abstraction_tendency": 0.25}, ["creative_mode", "writing"], layer="sub", subdimension_weights={"switching_tendency": -1.0}),
        make_item("sub-exec-closure-1", "比起不断开新头，我更在意把已经铺开的事真正收住。", {"execution_drive": 0.8, "planning_preference": 0.2}, ["project", "work"], layer="sub", subdimension_weights={"closure_strength": 1.0}, module_affinities={"project_role": 0.6}),
        make_item("sub-exec-closure-2", "如果一件事最后只差一点就能合上，我通常很难心安理得地把它晾着。", {"execution_drive": 0.8, "emotional_stability": 0.2}, ["work", "home"], layer="sub", subdimension_weights={"closure_strength": 1.0}),
        make_item("sub-exec-closure-3", "到了收尾阶段，我对“差不多就行”的容忍度往往会明显下降。", {"execution_drive": 0.75, "planning_preference": 0.25}, ["project", "creative_mode"], layer="sub", subdimension_weights={"closure_strength": 1.0}),
        make_item("sub-exec-closure-4", "清单只剩最后几步收口动作时，我常想一鼓作气把它们合完再走。", {"execution_drive": 0.8, "planning_preference": 0.2}, ["home", "admin"], layer="sub", subdimension_weights={"closure_strength": 1.0}),
        make_item("module-study-1", "一起学习时，我会下意识判断此刻谁适合拆题、谁适合推进、谁适合收束。", {"planning_preference": 0.4, "social_initiative": 0.3, "execution_drive": 0.3}, ["study", "team_mode"], layer="module", module_affinities={"study_style": 1.0, "team_mode": 0.6}),
        make_item("module-chat-1", "网聊时，我通常能很快判断眼下该轻松接话，还是直接把话题往前推。", {"social_stimulation_tolerance": 0.3, "social_initiative": 0.4, "autonomous_judgment": 0.3}, ["online", "chat_mode"], layer="module", module_affinities={"chat_mode": 1.0}),
        make_item("module-conflict-1", "处理分歧时，我更想先把真正卡住的点找出来，而不是先争气势。", {"emotional_stability": 0.45, "abstraction_tendency": 0.3, "competition_cooperation": -0.25}, ["conflict", "work"], layer="module", module_affinities={"conflict_mode": 1.0}),
        make_item("module-creative-1", "做创作时，我更像是在摸一个还没定型的方向，而不是照着蓝图逐项施工。", {"novelty_seeking": 0.45, "abstraction_tendency": 0.3, "risk_tolerance": 0.25}, ["creative_mode", "leisure"], layer="module", module_affinities={"creative_mode": 1.0}),
        make_item("module-team-1", "临时组队后，我通常很快会判断这队现在该冲、该拆，还是该先稳住。", {"social_initiative": 0.35, "planning_preference": 0.35, "autonomous_judgment": 0.3}, ["team_mode", "game"], layer="module", module_affinities={"team_mode": 1.0}),
        make_item("cross-open-source-1", "开源协作里，issue 已经堆着却没人拆时，我常会先把它切成几块可处理的小任务。", {"planning_preference": 0.45, "social_initiative": 0.3, "execution_drive": 0.25}, ["open_source", "project"], module_affinities={"project_role": 0.7, "study_style": 0.4}, allow_rewrite=True),
        make_item("cross-reading-group-1", "读书会如果一直在飘感想、没人收束，我常会把分歧背后的结构先拎出来。", {"abstraction_tendency": 0.5, "social_initiative": 0.2, "planning_preference": 0.3}, ["reading_group", "study"], module_affinities={"study_style": 0.8}),
        make_item("cross-rpg-1", "跑团或桌游局一乱起来时，我往往会一边读场面，一边把队伍节奏往回拽。", {"social_initiative": 0.35, "planning_preference": 0.35, "autonomous_judgment": 0.3}, ["rpg", "boardgame"], module_affinities={"team_mode": 0.9}),
        make_item("cross-fandom-1", "做设定考据或小圈子讨论时，我通常不会满足于“好玩就行”，还会追问规则能不能自洽。", {"abstraction_tendency": 0.55, "novelty_seeking": 0.25, "autonomous_judgment": 0.2}, ["fandom", "analysis"], allow_rewrite=True),
        make_item("module-study-2", "学术讨论、读书会或技术共读里，我会自然判断现在更该扩材料、收概念，还是落到具体问题。", {"planning_preference": 0.35, "abstraction_tendency": 0.35, "social_initiative": 0.3}, ["reading_group", "research"], layer="module", module_affinities={"study_style": 1.0}, allow_rewrite=True),
        make_item("module-chat-2", "论坛、群聊或评论区里，我常能很快分辨此刻该抛梗、补信息，还是把讨论拉回主线。", {"social_stimulation_tolerance": 0.35, "social_initiative": 0.35, "autonomous_judgment": 0.3}, ["forum", "online"], layer="module", module_affinities={"chat_mode": 1.0}),
        make_item("module-conflict-2", "做 code review、设定争论或观点辩论时，我更想先找到真正的断点，而不是先赢气势。", {"emotional_stability": 0.45, "abstraction_tendency": 0.3, "competition_cooperation": -0.25}, ["open_source", "critique"], layer="module", module_affinities={"conflict_mode": 1.0}),
        make_item("module-creative-2", "做独立游戏、写设定、剪片子或搭世界观时，我通常会在半成形阶段持续试错，不会太早把方向封死。", {"novelty_seeking": 0.45, "abstraction_tendency": 0.25, "risk_tolerance": 0.3}, ["indie_game", "creator"], layer="module", module_affinities={"creative_mode": 1.0}, allow_rewrite=True),
        make_item("module-team-2", "黑客松、临时项目组或活动筹备局里，我常会很快判断这拨人现在该分工、冲刺，还是先稳住。", {"social_initiative": 0.35, "planning_preference": 0.35, "execution_drive": 0.3}, ["hackathon", "event"], layer="module", module_affinities={"team_mode": 1.0}, allow_rewrite=True),
        make_item("anchor-social-1", "进入一个新场域后，要是一直没人起头，我通常会觉得应该有人先把局面点亮。", {"social_initiative": 1.0}, ["event", "unknown_group"], is_anchor=True),
        make_item("anchor-abstract-1", "只看做法、不追背后结构，会让我觉得自己其实还没真的理解。", {"abstraction_tendency": 1.0}, ["study", "analysis"], is_anchor=True),
        make_item("anchor-plan-1", "重要任务开始前，如果脑中没有基本结构，我会明显不踏实。", {"planning_preference": 1.0}, ["work", "project"], is_anchor=True),
        make_item("anchor-exec-1", "决定要做一件事后，我通常会很快把它推成一个能看见的起点。", {"execution_drive": 1.0}, ["project"], is_anchor=True),
        make_item("core-social-8", "讨论课老师抛出问题后全场短暂停住时，只要我有想法，我往往会先接第一句。", {"social_initiative": 1.0}, ["study", "public"]),
        make_item("core-social-9", "第一次参加一个半陌生的协作会，如果场子一直悬着，我常会先把话题往具体问题上落。", {"social_initiative": 1.0}, ["meeting", "unknown_group"]),
        make_item("core-decision-6", "两篇资料都像样、结论却相反时，我通常更愿意自己裁断，而不是先等谁来拍板。", {"autonomous_judgment": 1.0}, ["research", "reading"]),
        make_item("core-decision-7", "会上已经有主流意见时，只要我觉得方向不对，我一般不会因为资历差距就放弃自己的判断。", {"autonomous_judgment": 1.0}, ["work", "meeting"]),
        make_item("core-plan-6", "一周里杂事很多时，我会先把它们装进一个顺序清楚的框架里，再开始处理。", {"planning_preference": 1.0}, ["home", "admin"]),
        make_item("core-plan-7", "写长笔记或研究综述前，我通常会先搭章节骨架，而不是边写边找路。", {"planning_preference": 1.0}, ["research", "writing"]),
        make_item("core-risk-6", "一个方向只要上限足够高，哪怕前期路径还很糊，我也愿意先压一点筹码。", {"risk_tolerance": 1.0}, ["startup", "project"]),
        make_item("core-abstract-6", "看论文或教程时，我会本能地区分：哪些只是技巧，哪些才是可迁移的结构。", {"abstraction_tendency": 1.0}, ["reading", "research"]),
        make_item("core-novelty-4", "新工具刚出来、文档还不成熟时，我通常也愿意亲自摸一遍它的边界。", {"novelty_seeking": 1.0}, ["maker", "online"]),
        make_item("core-competition-4", "同样是一起做事，如果能隐约看出彼此谁做得更漂亮，我的状态通常会更满。", {"competition_cooperation": 1.0}, ["study", "project"]),
        make_item("core-emotion-5", "被老师、同伴或审稿式反馈直接指出硬伤后，我通常还能继续就事论事地改。", {"emotional_stability": 1.0}, ["critique", "research"]),
        make_item("core-execution-5", "一个系统已经搭出雏形后，我通常会接着把命名、归档和收尾也补齐。", {"execution_drive": 1.0}, ["admin", "knowledge_base"]),
        make_item("sub-social-entry-5", "刚换到新的讨论桌，只要气氛不算僵，我通常很快就会把第一句说出去。", {"social_initiative": 0.7, "social_stimulation_tolerance": 0.3}, ["study", "unknown_group"], layer="sub", subdimension_weights={"entry_speed": 1.0}),
        make_item("sub-social-conflict-5", "会里已经出现明显误解时，只要我看出来了，一般不会一直等别人先纠正。", {"social_initiative": 0.7, "emotional_stability": 0.3}, ["critique", "meeting"], layer="sub", subdimension_weights={"conflict_speaking_threshold": 1.0}),
        make_item("sub-decision-authority-5", "就算某篇文章被很多人当成标准答案，我也还是会先判断它有没有偷换问题。", {"autonomous_judgment": 0.75, "abstraction_tendency": 0.25}, ["research", "reading"], layer="sub", subdimension_weights={"authority_dependence": -1.0}),
        make_item("sub-decision-ambiguity-5", "项目还处在需求和路径都没完全定型的阶段时，我也能接受先做一个试探版。", {"risk_tolerance": 0.6, "autonomous_judgment": 0.4}, ["startup", "project"], layer="sub", subdimension_weights={"ambiguity_tolerance": 1.0}),
        make_item("sub-exec-start-5", "想法一旦够清楚能开写，我通常会先把提纲或第一页做出来，而不是继续憋。", {"execution_drive": 0.7, "planning_preference": 0.3}, ["research", "writing"], layer="sub", subdimension_weights={"start_speed": 1.0}),
        make_item("sub-plan-switch-5", "做到一半忽然冒出更优雅的方案时，我会先算切换成本，不会立刻推翻重来。", {"planning_preference": 0.8, "novelty_seeking": -0.2}, ["research", "project"], layer="sub", subdimension_weights={"switching_tendency": -1.0}),
        make_item("sub-exec-closure-5", "资料已经整理到最后一小段时，我通常会想顺手把索引、命名和归档一起封口。", {"execution_drive": 0.8, "planning_preference": 0.2}, ["knowledge_base", "admin"], layer="sub", subdimension_weights={"closure_strength": 1.0}),
        make_item("module-study-3", "共读或讨论一篇材料时，我会自然判断现在更该补背景、抠定义，还是转向核心问题。", {"planning_preference": 0.35, "abstraction_tendency": 0.35, "social_initiative": 0.3}, ["reading", "research"], layer="module", module_affinities={"study_style": 1.0}),
        make_item("module-chat-3", "线上聊天里，我通常能很快看出来对方此刻更需要情绪接住，还是信息推进。", {"social_stimulation_tolerance": 0.35, "social_initiative": 0.35, "autonomous_judgment": 0.3}, ["friends", "online"], layer="module", module_affinities={"chat_mode": 1.0}),
        make_item("module-conflict-3", "协作卡住时，我更想先确认到底是目标冲突、信息缺口，还是分工失衡。", {"emotional_stability": 0.45, "abstraction_tendency": 0.3, "competition_cooperation": -0.25}, ["meeting", "project"], layer="module", module_affinities={"conflict_mode": 1.0}),
        make_item("module-creative-3", "写东西时，我常会先放出几个半成形版本互相碰撞，而不是一开始就押单一路线。", {"novelty_seeking": 0.45, "abstraction_tendency": 0.3, "risk_tolerance": 0.25}, ["writing", "creative_mode"], layer="module", module_affinities={"creative_mode": 1.0}),
        make_item("module-team-3", "一个新团队刚开始磨合时，我通常会先判断现在最缺的是定角色、定节奏，还是定边界。", {"social_initiative": 0.35, "planning_preference": 0.35, "autonomous_judgment": 0.3}, ["project", "meeting"], layer="module", module_affinities={"team_mode": 1.0}),
        make_item("cross-research-1", "研究讨论如果一直停在概念层，我常会一边抽结构，一边追问下一步到底能做成什么。", {"abstraction_tendency": 0.5, "execution_drive": 0.5}, ["research", "project"], module_affinities={"study_style": 0.5, "project_role": 0.5}),
        make_item("cross-home-admin-1", "家里待办一旦开始堆积，我通常会先把它们编排成顺序，然后按块清掉。", {"planning_preference": 0.5, "execution_drive": 0.5}, ["home", "admin"], module_affinities={"project_role": 0.4}),
    ]
